# Builder.
FROM node:16-alpine as builder

WORKDIR /app

COPY ./prisma ./prisma
COPY ./package.json ./package.json

RUN npm install

COPY . .

RUN npm run build

EXPOSE 8080
CMD [ "npm", "run" ,"start:prod" ]