# Builder.
FROM node:14-alpine as builder
WORKDIR /app

COPY . .
RUN npm ci
RUN npx ng build --configuration=production

# Main.
FROM nginx:alpine
WORKDIR /app

COPY --from=builder /app/dist/movies-frontend /usr/share/nginx/html
COPY ./tools/nginx/angular.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
